# .streamlit/secrets.toml

[database]
driver = "ODBC Driver 17 for SQL Server"         # Nome exato do driver instalado
server = "DESKTOP-J9A3AKL\\SQLEXPRESS"           # Nome do servidor e instância
database = "smulado"                             # Nome do banco de dados
uid = "projeto"                                  # Usuário do SQL Server
pwd = "123456"                                   # Senha do usuário
encrypt = "no"                                   # Use "yes" se estiver usando SSL
trust_cert = "yes"                               # Confia no certificado do servidor
timeout = "30"                                   # Tempo limite da conexão em segundos

[api_keys]
GEMINI_API_KEY = "AIzaSyDz6PLA2Z1nT0-zuwZ-NehWFzU3pX7OMt0"
SERP_API_KEYS = "19d8eb43b1f35459653abe2248c3788d0a2fd3274587b3d92c7bc137724b5b10"
YOUTUBE_API_KEY = "AIzaSyDz6PLA2Z1nT0-zuwZ-NehWFzU3pX7OMt0"